Change java.arrays org and module name
ballerina-platform/ballerina-standard-library pull request #1166
Opened 2021-03-24 09:47 UTC by kalaiyarasiganeshalingam

## Purpose
$Subject

2021-03-24 10:22 UTC, daneshk approved these changes

2021-03-25 04:55 UTC, ThisaruGuruge requested changes
There are places where we special-cased the java.arrays version in `release/src/update_distribution.py`. We have to update that too.

2021-03-25 08:35 UTC, ThisaruGuruge commented on release/resources/module_list.json
> +        "module-ballerina-encoding",
Why are we adding the encoding package again?

2021-03-25 08:35 UTC, ThisaruGuruge commented on release/resources/module_list.json
> -        "module-ballerina-url",
Mistake?

2021-03-25 08:41 UTC, kalaiyarasiganeshalingam commented on release/resources/module_list.json
> -        "module-ballerina-url",
Yes.

2021-03-25 08:48 UTC, ThisaruGuruge approved these changes

2021-03-25 09:12 UTC, merged